server:
  port: 9090
spring:
  # Database
  datasource:
    driver-class-name:  org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security
    username: cos
    password: cos1234
  # JPA
  jpa:
    properties:
      sql: true
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true

